# Generated by Django 4.0.1 on 2022-01-25 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Antenna name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('callsign', models.CharField(help_text='Callsign', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Maidenhead grid', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transceiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Transceiver name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HomeStation',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='station.station')),
            ],
            bases=('station.station',),
        ),
    ]
