# Generated by Django 4.0.1 on 2022-01-25 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestation',
            name='operators',
            field=models.ManyToManyField(help_text='Operators of this station', to=settings.AUTH_USER_MODEL),
        ),
    ]
