# Generated by Django 4.0.1 on 2022-01-25 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qsl_log', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_operated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remote_antenna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry_as_remote', to='station.antenna'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remote_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry_as_remote', to='station.station'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remote_transceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry_as_remote', to='station.transceiver'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry_as_home', to='station.homestation'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='transceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry_as_home', to='station.transceiver'),
        ),
    ]
