# Generated by Django 4.0.1 on 2022-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsl_log', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='mode',
            field=models.CharField(default='', help_text='Operating mode', max_length=20),
            preserve_default=False,
        ),
    ]
